"""Demo fixture.

This is an explicit, clearly-labelled demo close, not a template that new closes are
cloned from. Two distinctions from the fixture it replaces:

  * its source documents are real PDF bytes in storage, so generation and export
    actually have something to operate on;
  * its audit trail records the seeded actions with matching actors and timestamps, so
    the trail agrees with the state instead of contradicting it.
"""

from datetime import datetime, timedelta, timezone
from typing import Any

from ..db import store
from . import storage
from .closes import audit, build_close, new_id
from .pdf import build_pdf
from .templates import DEFAULT_TEMPLATE_ID, suggest_document_type

DEMO_CLOSE_ID = "close-demo-march-2026"

_OWNER = {"id": "user_demo_owner", "name": "Abhinay Reddy", "role": "Controller"}
_PREPARER = {"id": "user_demo_preparer", "name": "Mira Shah", "role": "Preparer"}
_REVIEWER = {"id": "user_demo_reviewer", "name": "Priya Nair", "role": "Finance Manager"}

# filename -> (classified type or None, body lines)
_DEMO_DOCUMENTS: list[tuple[str, list[str]]] = [
    ("Trial Balance.pdf", ["Total debits   12,480,220.00", "Total credits  12,480,220.00", "Variance             0.00"]),
    ("Bank Recon.pdf", ["Statement balance  3,204,118.42", "Book balance       3,204,118.42", "Unreconciled items: none"]),
    ("AR Memo.pdf", ["Gross receivables  4,118,900.00", "Allowance           (212,400.00)", "Net receivables    3,906,500.00"]),
    ("Revenue Memo.pdf", ["March revenue      6,842,110.00", "Prior month        6,311,880.00", "Movement           +8.4%"]),
    ("Accrual Support.pdf", ["Vendor accruals      884,300.00", "One vendor accrual pending controller review"]),
    ("AP Aging.pdf", ["Current           1,940,220.00", "31-60 days          214,880.00", "60+ days             18,400.00"]),
    ("Payroll Register.pdf", ["Gross pay         2,118,400.00", "Employer taxes      264,120.00", "Net pay           1,702,880.00"]),
    ("Fixed Assets.pdf", ["Opening NBV      18,440,000.00", "Additions           640,000.00", "Depreciation       (302,100.00)"]),
]

# Left unclassified so the demo opens with a real "Confirm mapping" action outstanding.
_UNCLASSIFIED = {"Revenue Memo.pdf"}

_COMPLETED_CHECKLIST_TITLES = {
    "Trial balance reviewed",
    "Bank reconciliation complete",
    "AR reconciliation complete",
    "Payroll reconciliation",
    "Fixed asset roll-forward",
}


def _iso(base: datetime, minutes: int) -> str:
    return (base + timedelta(minutes=minutes)).isoformat()


def build_demo_close() -> dict[str, Any]:
    base = datetime.now(timezone.utc).replace(microsecond=0) - timedelta(hours=4)

    close = build_close(
        entity="Acme India Pvt Ltd",
        period="2026-03",
        owner=_OWNER["name"],
        due_date="2026-04-05",
        template_id=DEFAULT_TEMPLATE_ID,
        actor=_OWNER,
        close_id=DEMO_CLOSE_ID,
    )
    close["is_demo"] = True
    close["created_at"] = _iso(base, 0)
    close["audit"][0]["created_at"] = _iso(base, 0)

    minute = 5
    for filename, body in _DEMO_DOCUMENTS:
        document_id = new_id("doc")
        content = build_pdf(
            f"{filename.rsplit('.', 1)[0]} - Acme India Pvt Ltd - March 2026",
            [*body, "", "Synthetic demo document generated by CloseOrbit. Not a real financial record."],
        )
        key = f"closes/{close['id']}/documents/{document_id}/{filename}"
        stored = storage.put_bytes(key, content)

        classified = filename not in _UNCLASSIFIED
        suggested = suggest_document_type(filename, close["required_document_types"])
        close["documents"].append(
            {
                "id": document_id,
                "filename": filename,
                "content_type": "application/pdf",
                "document_type": suggested if classified else None,
                "suggested_type": suggested,
                "status": "READY" if classified else "PROCESSING",
                "size": stored["size"],
                "sha256": stored["sha256"],
                "storage_key": key,
                "uploaded_by": _PREPARER["name"],
                "uploaded_at": _iso(base, minute),
            }
        )
        audit(close, "DOCUMENT_UPLOADED", _PREPARER, filename, at=_iso(base, minute))
        if classified:
            audit(close, "DOCUMENT_CLASSIFIED", _PREPARER, f"{filename} -> {suggested}", at=_iso(base, minute + 1))
        minute += 4

    for item in close["checklist"]:
        if item["title"] in _COMPLETED_CHECKLIST_TITLES:
            item.update({"status": "COMPLETE", "completed_by": _PREPARER["name"], "completed_at": _iso(base, minute)})
            audit(close, "CHECKLIST_COMPLETED", _PREPARER, item["title"], at=_iso(base, minute))
            minute += 3

    for signoff, actor in ((close["signoffs"][0], _OWNER), (close["signoffs"][1], _REVIEWER)):
        signoff.update(
            {
                "status": "APPROVED",
                "person": actor["name"],
                "signed_by": actor["id"],
                "signed_at": _iso(base, minute),
            }
        )
        audit(close, "SIGNOFF_APPROVED", actor, signoff["role"], at=_iso(base, minute))
        minute += 6

    return close


# Fields added after the first databases were written. A close stored before they
# existed must not render as half-populated, so they are backfilled on boot.
_BACKFILLED_FIELDS: dict[str, Any] = {
    "generating_since": None,
    "superdocs_working_document_id": None,
    "superdocs_export": None,
    "superdocs_operations": [],
    "generated_artifacts": [],
}


def backfill_closes() -> None:
    """Add any missing fields to closes written by an earlier build."""
    for close in store.list_closes():
        missing = {key: value for key, value in _BACKFILLED_FIELDS.items() if key not in close}
        if not missing:
            continue

        def mutator(current: dict[str, Any], missing: dict[str, Any] = missing) -> None:
            for key, value in missing.items():
                current.setdefault(key, value)
            # An export recorded before SuperDocs was part of the flow predates the
            # contract, so it cannot satisfy the gate any more.
            if current.get("exported") and not current.get("superdocs_export"):
                current["exported"] = False
                current["export"] = None

        try:
            store.mutate_close(close["id"], mutator)
        except KeyError:
            continue


def ensure_demo_close() -> None:
    """Create the demo close once. Never overwrites an existing one."""
    backfill_closes()
    if store.close_exists(DEMO_CLOSE_ID):
        return
    store.save_close(build_demo_close())
